BBBBBBB BBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXXXXXX
        XXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'login page') XXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'login') XX
        XXXXXXX
        XX XXXXXXXXXXXXX XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'forget password') XXXX
    XXXXXXXXX
BBBBBBBB
