BBBBBBB BBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'are you sure for exit ') XXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'logout') XX
        XXXXXXX
    XXXXXXXXX
BBBBBBBB
