BBBBBBB BBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXXXXXX
        XXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'change password') XXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'change password') XX
        XXXXXXX
    XXXXXXXXX
BBBBBBBB
