BBBBBBB BBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXXXXXX
        XXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'signup page') XXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'signup') XX
        XXXXXXX
    XXXXXXXXX
BBBBBBBB
