# Generated by Django 4.1.7 on 2023-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='book_image/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
